# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/bd/dkong/ip/dkong_framedoubler_slow_0_0/dkong_framedoubler_slow_0_0.xci
# IP: The module: 'dkong_framedoubler_slow_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/framedoubler_mem/framedoubler_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==framedoubler_mem || ORIG_REF_NAME==framedoubler_mem} -quiet] -quiet

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/framedoubler_mem/framedoubler_mem_ooc.xdc

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/bd/dkong/ip/dkong_framedoubler_slow_0_0/dkong_framedoubler_slow_0_0.xci
# IP: The module: 'dkong_framedoubler_slow_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/framedoubler_mem/framedoubler_mem.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==framedoubler_mem || ORIG_REF_NAME==framedoubler_mem} -quiet] -quiet

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/framedoubler_mem/framedoubler_mem_ooc.xdc
