# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/bd/dkong/ip/dkong_dkong_system_wrapper_0_0/dkong_dkong_system_wrapper_0_0.xci
# IP: The module: 'dkong_dkong_system_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/cpu_program_rom/cpu_program_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_program_rom || ORIG_REF_NAME==cpu_program_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3f_banked_rom/sou_3f_banked_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sou_3f_banked_rom || ORIG_REF_NAME==sou_3f_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3h_banked_rom/sou_3h_banked_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sou_3h_banked_rom || ORIG_REF_NAME==sou_3h_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2f_banked_prom/palette_2f_banked_prom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==palette_2f_banked_prom || ORIG_REF_NAME==palette_2f_banked_prom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2e_banked_prom/palette_2e_banked_prom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==palette_2e_banked_prom || ORIG_REF_NAME==palette_2e_banked_prom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7f_banked_rom/obj_7f_banked_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7f_banked_rom || ORIG_REF_NAME==obj_7f_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7e_banked_rom/obj_7e_banked_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7e_banked_rom || ORIG_REF_NAME==obj_7e_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7d_banked_rom/obj_7d_banked_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7d_banked_rom || ORIG_REF_NAME==obj_7d_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7c_banked_rom/obj_7c_banked_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7c_banked_rom || ORIG_REF_NAME==obj_7c_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3n_banked_rom/tile_3n_banked_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tile_3n_banked_rom || ORIG_REF_NAME==tile_3n_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3p_banked_rom/tile_3p_banked_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tile_3p_banked_rom || ORIG_REF_NAME==tile_3p_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_2n_banked_prom/tile_2n_banked_prom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tile_2n_banked_prom || ORIG_REF_NAME==tile_2n_banked_prom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/cpu_program_banked_rom/cpu_program_banked_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_program_banked_rom || ORIG_REF_NAME==cpu_program_banked_rom} -quiet] -quiet

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/cpu_program_rom/cpu_program_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3f_banked_rom/sou_3f_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3h_banked_rom/sou_3h_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2f_banked_prom/palette_2f_banked_prom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2e_banked_prom/palette_2e_banked_prom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7f_banked_rom/obj_7f_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7e_banked_rom/obj_7e_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7d_banked_rom/obj_7d_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7c_banked_rom/obj_7c_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3n_banked_rom/tile_3n_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3p_banked_rom/tile_3p_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_2n_banked_prom/tile_2n_banked_prom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/cpu_program_banked_rom/cpu_program_banked_rom_ooc.xdc

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/bd/dkong/ip/dkong_dkong_system_wrapper_0_0/dkong_dkong_system_wrapper_0_0.xci
# IP: The module: 'dkong_dkong_system_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/cpu_program_rom/cpu_program_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_program_rom || ORIG_REF_NAME==cpu_program_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3f_banked_rom/sou_3f_banked_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sou_3f_banked_rom || ORIG_REF_NAME==sou_3f_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3h_banked_rom/sou_3h_banked_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sou_3h_banked_rom || ORIG_REF_NAME==sou_3h_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2f_banked_prom/palette_2f_banked_prom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==palette_2f_banked_prom || ORIG_REF_NAME==palette_2f_banked_prom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2e_banked_prom/palette_2e_banked_prom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==palette_2e_banked_prom || ORIG_REF_NAME==palette_2e_banked_prom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7f_banked_rom/obj_7f_banked_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7f_banked_rom || ORIG_REF_NAME==obj_7f_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7e_banked_rom/obj_7e_banked_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7e_banked_rom || ORIG_REF_NAME==obj_7e_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7d_banked_rom/obj_7d_banked_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7d_banked_rom || ORIG_REF_NAME==obj_7d_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7c_banked_rom/obj_7c_banked_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7c_banked_rom || ORIG_REF_NAME==obj_7c_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3n_banked_rom/tile_3n_banked_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tile_3n_banked_rom || ORIG_REF_NAME==tile_3n_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3p_banked_rom/tile_3p_banked_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tile_3p_banked_rom || ORIG_REF_NAME==tile_3p_banked_rom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_2n_banked_prom/tile_2n_banked_prom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tile_2n_banked_prom || ORIG_REF_NAME==tile_2n_banked_prom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/cpu_program_banked_rom/cpu_program_banked_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_program_banked_rom || ORIG_REF_NAME==cpu_program_banked_rom} -quiet] -quiet

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/cpu_program_rom/cpu_program_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3f_banked_rom/sou_3f_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3h_banked_rom/sou_3h_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2f_banked_prom/palette_2f_banked_prom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2e_banked_prom/palette_2e_banked_prom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7f_banked_rom/obj_7f_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7e_banked_rom/obj_7e_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7d_banked_rom/obj_7d_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7c_banked_rom/obj_7c_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3n_banked_rom/tile_3n_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3p_banked_rom/tile_3p_banked_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_2n_banked_prom/tile_2n_banked_prom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/cpu_program_banked_rom/cpu_program_banked_rom_ooc.xdc
