# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/bd/dkong/ip/dkong_dkong_system_wrapper_0_0/dkong_dkong_system_wrapper_0_0.xci
# IP: The module: 'dkong_dkong_system_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3f_rom/sou_3f_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sou_3f_rom || ORIG_REF_NAME==sou_3f_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3h_rom/sou_3h_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sou_3h_rom || ORIG_REF_NAME==sou_3h_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2f_prom/palette_2f_prom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==palette_2f_prom || ORIG_REF_NAME==palette_2f_prom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2e_prom/palette_2e_prom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==palette_2e_prom || ORIG_REF_NAME==palette_2e_prom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7f_rom/obj_7f_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7f_rom || ORIG_REF_NAME==obj_7f_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7e_rom/obj_7e_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7e_rom || ORIG_REF_NAME==obj_7e_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7d_rom/obj_7d_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7d_rom || ORIG_REF_NAME==obj_7d_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7c_rom/obj_7c_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7c_rom || ORIG_REF_NAME==obj_7c_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3n_rom/tile_3n_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tile_3n_rom || ORIG_REF_NAME==tile_3n_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3p_rom/tile_3p_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tile_3p_rom || ORIG_REF_NAME==tile_3p_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_2n_prom/tile_2n_prom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tile_2n_prom || ORIG_REF_NAME==tile_2n_prom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/cpu_program_rom_dp/cpu_program_rom_dp.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_program_rom_dp || ORIG_REF_NAME==cpu_program_rom_dp} -quiet] -quiet

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3f_rom/sou_3f_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3h_rom/sou_3h_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2f_prom/palette_2f_prom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2e_prom/palette_2e_prom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7f_rom/obj_7f_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7e_rom/obj_7e_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7d_rom/obj_7d_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7c_rom/obj_7c_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3n_rom/tile_3n_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3p_rom/tile_3p_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_2n_prom/tile_2n_prom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/cpu_program_rom_dp/cpu_program_rom_dp_ooc.xdc

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/bd/dkong/ip/dkong_dkong_system_wrapper_0_0/dkong_dkong_system_wrapper_0_0.xci
# IP: The module: 'dkong_dkong_system_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3f_rom/sou_3f_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sou_3f_rom || ORIG_REF_NAME==sou_3f_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3h_rom/sou_3h_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sou_3h_rom || ORIG_REF_NAME==sou_3h_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2f_prom/palette_2f_prom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==palette_2f_prom || ORIG_REF_NAME==palette_2f_prom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2e_prom/palette_2e_prom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==palette_2e_prom || ORIG_REF_NAME==palette_2e_prom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7f_rom/obj_7f_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7f_rom || ORIG_REF_NAME==obj_7f_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7e_rom/obj_7e_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7e_rom || ORIG_REF_NAME==obj_7e_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7d_rom/obj_7d_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7d_rom || ORIG_REF_NAME==obj_7d_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7c_rom/obj_7c_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==obj_7c_rom || ORIG_REF_NAME==obj_7c_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3n_rom/tile_3n_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tile_3n_rom || ORIG_REF_NAME==tile_3n_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3p_rom/tile_3p_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tile_3p_rom || ORIG_REF_NAME==tile_3p_rom} -quiet] -quiet

# IP: C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_2n_prom/tile_2n_prom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==tile_2n_prom || ORIG_REF_NAME==tile_2n_prom} -quiet] -quiet

# IP: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/cpu_program_rom_dp/cpu_program_rom_dp.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_program_rom_dp || ORIG_REF_NAME==cpu_program_rom_dp} -quiet] -quiet

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3f_rom/sou_3f_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/sou_3h_rom/sou_3h_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2f_prom/palette_2f_prom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/palette_2e_prom/palette_2e_prom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7f_rom/obj_7f_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7e_rom/obj_7e_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7d_rom/obj_7d_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/obj_7c_rom/obj_7c_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3n_rom/tile_3n_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_3p_rom/tile_3p_rom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/tile_2n_prom/tile_2n_prom_ooc.xdc

# XDC: c:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.srcs/sources_1/ip/cpu_program_rom_dp/cpu_program_rom_dp_ooc.xdc
