webtalk_init -webtalk_dir C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.sim/sim_1/behav/xsim/xsim.dir/fb_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Feb 23 21:02:03 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6aae3975-9d73-4d5e-bd5a-30296574356a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b79cc937ef9a44f39b020a5ca4c4adb1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "105" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "160 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "172.94_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17880_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3259789703 -regid "" -xml C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.sim/sim_1/behav/xsim/xsim.dir/fb_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.sim/sim_1/behav/xsim/xsim.dir/fb_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Steven/Documents/HDL/vivado/dkong_system/dkong_system.sim/sim_1/behav/xsim/xsim.dir/fb_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
